Repository slatecurrency/slate, pull requests merged in 2019-03, with the labels that each got.

#15 [build] patch to get gitian aarch64 built under gcc 5
  contrib/gitian-descriptors/gitian-aarch64.yml
Labels: Build system

#13 Tests: Update and add some new linter tests to the Travis builds
  .travis.yml
  test/lint/lint-all.sh
  test/lint/lint-format-strings.py
  test/lint/lint-format-strings.sh
  test/lint/lint-python.sh
  test/lint/lint-whitespace.sh
  test/lint/logprint-scanner.py
Labels: Tests

#22 [build][tests] update travis lint scripts
  .travis.yml
  .travis/lint_06_script.sh
Labels: Build system, Linux/Unix, Scripts and tools

#16 [build] fix a few compilation issues with Clang 7 and -Werror
  build-aux/m4/ax_boost_chrono.m4
  build-aux/m4/ax_boost_unit_test_framework.m4
  configure.ac
Labels: Build system
